import {
  FaRegEnvelope,
  FaPlay,
  FaAward,
  FaChevronLeft,
  FaChevronRight,
  FaDna,
  FaFacebook,
  FaFlask,
  FaHandHoldingMedical,
  FaHeartbeat,
  FaHospitalUser,
  FaInstagram,
  FaLinkedin,
  FaLungs,
  FaNotesMedical,
  FaPills,
  FaQuoteRight,
  FaRegClock,
  FaThermometer,
  FaTwitter,
  FaUserMd,
  FaWheelchair,
  FaMedkit,
} from "react-icons/fa";
import { IoCheckmarkDoneSharp } from "react-icons/io5";
import { FaRegHospital, FaStaffSnake, FaMobile } from "react-icons/fa6";

export const Icon = {
  facebook: FaFacebook,
  twitter: FaTwitter,
  instagram: FaInstagram,
  linkedin: FaLinkedin,
  envelope: FaRegEnvelope,
  videoStart: FaPlay,
  arrowLeft: FaChevronLeft,
  arrowRight: FaChevronRight,
  mobile: FaMobile,
  clock: FaRegClock,
  check: IoCheckmarkDoneSharp,

  flask: FaFlask,
  handHoldingMedical: FaHandHoldingMedical,
  quote: FaQuoteRight,
  dna: FaDna,
  patch: FaAward,
  lungs: FaLungs,
  pills: FaPills,
  thermometer: FaThermometer,
  doctors: FaUserMd,
  heartbeat: FaHeartbeat,
  wheelchair: FaWheelchair,
  notesMedical: FaNotesMedical,
  hospitalUser: FaHospitalUser,
  hospital: FaRegHospital,
  medkit: FaMedkit,
  staffSnake: FaStaffSnake,
};
